// <auto-generated />
using System;
using FunerariaApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FunerariaApp.Migrations
{
    [DbContext(typeof(FunerariaDbContext))]
    [Migration("20260624011238_AgregarUsuarios")]
    partial class AgregarUsuarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FunerariaApp.Models.Ataud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SucursalId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.ToTable("Ataudes");
                });

            modelBuilder.Entity("FunerariaApp.Models.AtaudFoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AtaudId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AtaudId");

                    b.ToTable("AtaudFotos");
                });

            modelBuilder.Entity("FunerariaApp.Models.DocumentoFase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ArchivoUrl")
                        .HasColumnType("text");

                    b.Property<int>("FaseServicioId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaRecepcion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Recibido")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FaseServicioId");

                    b.ToTable("DocumentosFase");
                });

            modelBuilder.Entity("FunerariaApp.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Edad")
                        .HasColumnType("integer");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("FunerariaApp.Models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("FunerariaApp.Models.FaseServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Completada")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaCompletada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<string>("NumeroFase")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("ServicioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServicioId");

                    b.ToTable("FasesServicio");
                });

            modelBuilder.Entity("FunerariaApp.Models.Renta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DireccionServicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaRegresoEstimada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaRegresoReal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MapaUrl")
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.ToTable("Rentas");
                });

            modelBuilder.Entity("FunerariaApp.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtaudId")
                        .HasColumnType("integer");

                    b.Property<string>("DireccionRecoleccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EquipoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MapaRecoleccionUrl")
                        .HasColumnType("text");

                    b.Property<string>("NombreFinado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text");

                    b.Property<int>("SucursalId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AtaudId");

                    b.HasIndex("EquipoId");

                    b.HasIndex("SucursalId");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("FunerariaApp.Models.ServicioEmpleado", b =>
                {
                    b.Property<int>("ServicioId")
                        .HasColumnType("integer");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("integer");

                    b.HasKey("ServicioId", "EmpleadoId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("ServicioEmpleados");
                });

            modelBuilder.Entity("FunerariaApp.Models.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("FunerariaApp.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("FunerariaApp.Models.Vela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Costo")
                        .HasColumnType("numeric");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Servicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Velas");
                });

            modelBuilder.Entity("FunerariaApp.Models.Ataud", b =>
                {
                    b.HasOne("FunerariaApp.Models.Sucursal", "Sucursal")
                        .WithMany("Ataudes")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("FunerariaApp.Models.AtaudFoto", b =>
                {
                    b.HasOne("FunerariaApp.Models.Ataud", "Ataud")
                        .WithMany("Fotos")
                        .HasForeignKey("AtaudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ataud");
                });

            modelBuilder.Entity("FunerariaApp.Models.DocumentoFase", b =>
                {
                    b.HasOne("FunerariaApp.Models.FaseServicio", "FaseServicio")
                        .WithMany("Documentos")
                        .HasForeignKey("FaseServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FaseServicio");
                });

            modelBuilder.Entity("FunerariaApp.Models.FaseServicio", b =>
                {
                    b.HasOne("FunerariaApp.Models.Servicio", "Servicio")
                        .WithMany("Fases")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("FunerariaApp.Models.Renta", b =>
                {
                    b.HasOne("FunerariaApp.Models.Equipo", "Equipo")
                        .WithMany("Rentas")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");
                });

            modelBuilder.Entity("FunerariaApp.Models.Servicio", b =>
                {
                    b.HasOne("FunerariaApp.Models.Ataud", "Ataud")
                        .WithMany("Servicios")
                        .HasForeignKey("AtaudId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FunerariaApp.Models.Equipo", "Equipo")
                        .WithMany("Servicios")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FunerariaApp.Models.Sucursal", "Sucursal")
                        .WithMany("Servicios")
                        .HasForeignKey("SucursalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ataud");

                    b.Navigation("Equipo");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("FunerariaApp.Models.ServicioEmpleado", b =>
                {
                    b.HasOne("FunerariaApp.Models.Empleado", "Empleado")
                        .WithMany("ServicioEmpleados")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FunerariaApp.Models.Servicio", "Servicio")
                        .WithMany("ServicioEmpleados")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("FunerariaApp.Models.Ataud", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("FunerariaApp.Models.Empleado", b =>
                {
                    b.Navigation("ServicioEmpleados");
                });

            modelBuilder.Entity("FunerariaApp.Models.Equipo", b =>
                {
                    b.Navigation("Rentas");

                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("FunerariaApp.Models.FaseServicio", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("FunerariaApp.Models.Servicio", b =>
                {
                    b.Navigation("Fases");

                    b.Navigation("ServicioEmpleados");
                });

            modelBuilder.Entity("FunerariaApp.Models.Sucursal", b =>
                {
                    b.Navigation("Ataudes");

                    b.Navigation("Servicios");
                });
#pragma warning restore 612, 618
        }
    }
}
